---
output: html_document
---

# What lies beneath? Molecular evolution during the radiation of caecilian amphibians

### Abstract of the research article

**Background:** Evolution leaves an imprint in species through genetic change. At the molecular level, evolutionary changes can be explored by studying ratios of nucleotide substitutions. The interplay among molecular evolution, derived phenotypes, and ecological ranges can provide insights into adaptive radiations. Caecilians (order Gymnophiona), probably the least known of the major lineages of vertebrates, are limbless tropical amphibians, with adults of most species burrowing in soils (fossoriality). This enigmatic order of amphibians are very distinct phenotypically from other extant amphibians and likely from the ancestor of Lissamphibia, but little to nothing is known about the molecular changes underpinning their radiation. We hypothesised that colonization of various depths of tropical soils and of freshwater habitats presented new ecological opportunities to caecilians.  

**Results:** A total of 8540 candidate groups of orthologous genes from transcriptomic data of five species of caecilian amphibians and the genome of the frog Xenopus tropicalis were analysed in order to investigate the genetic machinery behind caecilian diversification. We found a total of 168 protein-coding genes with signatures of positive selection at different evolutionary times during the radiation of caecilians. The majority of these genes were related to functional elements of the cell membrane and extracellular matrix with expression in several different tissues. The first colonization of the tropical soils was connected to the largest number of protein-coding genes under positive selection in our analysis. From the results of our study, we highlighted molecular changes in genes involved in perception, reduction-oxidation processes, and aging that likely were involved in the adaptation to different soil strata.  

**Conclusions:** The genes inferred to have been under positive selection provide valuable insights into caecilian evolution, potentially underpin adaptations of caecilians to their extreme environments, and contribute to a better understanding of fossorial adaptations and molecular evolution in vertebrates.

### Data information

The data folder (data_Torres-Sánchez2019b) contains the 168 alignments in which signatures of positive selection were detected. Each file is a PHYLIP multiple sequence alignment named after the Ensembl identifiers of the *Xenopus* genes (Gene ID and transcript ID, e.g. ENSXETG00000000057.3_ENSXETT00000000095.3.fas.phy). Taxa are ordered as follow:   
seq1 - *Xenopus tropicalis*  
seq2 - *Rhinatrema bivittatum*  
seq3 - *Caecilia tentaculata*  
seq4 - *Typhlonectes compressicauda*  
seq5 - *Microcaecilia dermatophaga*  
seq6 - *Microcaecilia unicolor*  

### Citation

When using the alignment data please cite the following paper:  
Torres-Sánchez M, Gower DJ, Alvarez-Ponce D, Creevey CJ, Wilkinson M, and San Mauro D. 2019. What lies beneath? Molecular evolution during the radiation of caecilian amphibians. BMC Genomics. 20:354. (https://doi.org/10.1186/s12864-019-5694-1)





